#!/usr/bin/env python3
"""
Script to translate Chinese comments to English in counting_butterfly.py
"""

# Translation dictionary for common comments
translations = {
    # Top-level comments
    "# 初始化pygame": "# Initialize pygame",
    "# 初始化音频系统": "# Initialize audio system", 
    "# 游戏状态枚举": "# Game state enumeration",
    "# 暂停状态": "# Paused state",
    "# 游戏常量": "# Game constants",
    "# 统一蝴蝶高度（像素），可按需调整": "# Unified butterfly height (pixels), adjustable",
    "# 颜色定义 - 红蓝撞色": "# Color definitions - Red and Blue contrast",
    "# 创建游戏窗口": "# Create game window",
    "# 加载字体 - 使用Press Start 2P像素字体": "# Load font - Use Press Start 2P pixel font",
    "# 像素字体建议使用较小尺寸": "# Pixel font recommended to use smaller sizes",
    "# 如果字体加载失败，尝试使用系统字体": "# If font loading fails, try using system font",
    "# 加载背景图（可选）": "# Load background image (optional)",
    "# 加载音频文件": "# Load audio files",
    "# 尝试加载背景音乐（电子乐风格）": "# Try to load background music (electronic style)",
    "# 尝试加载倒计时音效": "# Try to load countdown sound effect",
    "# 尝试加载开始音效": "# Try to load start sound effect",
    "# 尝试加载按键音效": "# Try to load keypress sound effect",
    "# 尝试加载成功音效": "# Try to load success sound effect",
    "# 尝试加载错误音效": "# Try to load error sound effect",
    "# 辅助函数：绘制带白色描边的文字": "# Helper function: Draw text with white outline",
    "# 绘制描边（8个方向）": "# Draw outline (8 directions)",
    "# 绘制主文字": "# Draw main text",
    "# 像素风格蝴蝶类": "# Pixel-style butterfly class",
    "# 静态加载图片": "# Static image loading",
    "# 蝴蝶显示尺寸": "# Butterfly display size",
    "# 缩短单个蝴蝶存活时间": "# Shorten single butterfly lifetime",
    "# 蓝红交替": "# Alternate blue and red",
    "# 移动相关属性（第三关）": "# Movement attributes (Level 3)",
    "# 随机方向（360度）": "# Random direction (360 degrees)",
    "# 随机速度": "# Random speed",
    "# 如果是移动的蝴蝶，更新位置": "# If butterfly is moving, update position",
    "# 碰到边界反弹": "# Bounce off boundaries",
    "# 保持原始比例缩放，最大边为self.size": "# Maintain original aspect ratio, max side is self.size",
    "# 如果图片加载失败，用原有像素风后备绘制": "# If image loading fails, use fallback pixel art drawing",
    "# 加载角色精灵图片": "# Load character sprite images",
    "# 加载精灵文件（保留透明通道）": "# Load sprite file (preserve alpha channel)",
    "# 提取红色角色 - 使用整个图片": "# Extract red character - use entire image",
    "# 提取蓝色角色 - 使用整个图片": "# Extract blue character - use entire image",
    "# 加载音频文件": "# Load audio files",
    "# 加载蝴蝶图片（两种样式，可选）": "# Load butterfly images (two styles, optional)",
    "# 加载蓝色和红色蝴蝶图片": "# Load blue and red butterfly images",
    "# 将接近白色的像素变为透明": "# Make near-white pixels transparent",
    "# 不再加载任何图片，直接返回空列表，全部用像素风格程序绘制": "# No longer load images, return empty list, draw all with pixel art",
    "# 不再加载图片，全部用像素风格程序绘制": "# No longer load images, draw all with pixel art",
    "# 起伏/扇动效果（不依赖素材，可共用）": "# Flapping effect (not dependent on assets, can be shared)",
    "# 垂直轻微起伏，模拟飞舞": "# Slight vertical oscillation, simulate flight",
    "# 后备：绘制像素风蝴蝶": "# Fallback: Draw pixel-art butterfly",
    "# 玩家类": "# Player class",
    "# 处理输入 - 可以输入任意数字": "# Handle input - can enter any number",
    "# 上键/W键": "# Up key/W key",
    "# 每次增加1": "# Increase by 1 each time",
    "# 播放按键音效": "# Play keypress sound",
    "# 下键/S键": "# Down key/S key",
    "# 确保不小于0": "# Ensure not less than 0",
    "# 每次减少1": "# Decrease by 1 each time",
    "# 提交键": "# Submit key",
    "# 蝴蝶尺寸更大，带黑色外轮廓": "# Larger butterfly size with black outline",
    "# 如果有对应的精灵，使用它": "# If corresponding sprite exists, use it",
    "# 直接居中绘制精灵（无任何边框/背景）": "# Draw sprite centered (no border/background)",
    "# 成功绘制精灵，退出": "# Successfully drew sprite, exit",
    "# 如果精灵加载失败，使用后备方法": "# If sprite loading fails, use fallback method",
    "# 增强的后备绘制方法 - 更大更明显的角色": "# Enhanced fallback drawing - larger more visible character",
    "# 增大基础尺寸": "# Increase base size",
    "# 先绘制一个明显的背景边框": "# First draw visible background border",
    "# 白色背景": "# White background",
    "# 黑色边框": "# Black border",
    "# 头部 - 大圆形": "# Head - large circle",
    "# 眼睛": "# Eyes",
    "# 身体 - 矩形": "# Body - rectangle",
    "# 只负责玩家自身绘制，不绘制蝴蝶": "# Only draw player, not butterflies",
    "# 游戏主类": "# Main game class",
    "# 倒计时": "# Countdown",
    "# 上次播放倒计时音效的数字": "# Last number for countdown sound played",
    "# 暂停标志": "# Pause flag",
    "# 暂停前的状态": "# State before pause",
    "# 创建玩家（红色在右，蓝色在左，键位对应位置）": "# Create players (red on right, blue on left, keys match positions)",
    "# player1 = 红色，在右边，使用 UP/DOWN/ENTER": "# player1 = red, on right, uses UP/DOWN/ENTER",
    "# player2 = 蓝色，在左边，使用 W/S/SPACE": "# player2 = blue, on left, uses W/S/SPACE",
    "# 在游戏开始时就播放背景音乐": "# Play background music at game start",
    "# -1 表示循环播放": "# -1 means loop playback",
    "# 第三关的目标数量减半": "# Level 3 target count is half",
    "# 24的一半": "# Half of 24",
    "# 启动倒计时": "# Start countdown",
    "# 生成1-4只蝴蝶，在整个屏幕上方随机分布（不按颜色区分左右）": "# Generate 1-4 butterflies randomly across screen (not divided by color)",
    "# 玩家底座高度": "# Player base height",
    "# 计算当前蓝红蝴蝶数量，确保均衡生成": "# Count blue/red butterflies, ensure balanced generation",
    "# 交替生成蓝红蝴蝶": "# Alternate blue and red butterflies",
    "# 尝试找到不重叠的位置": "# Try to find non-overlapping position",
    "# X轴：在整个屏幕宽度范围内随机分布（不按颜色区分）": "# X-axis: Random across screen width (not divided by color)",
    "# 离边缘至少60像素": "# At least 60 pixels from edge",
    "# Y轴：玩家上方150~320像素随机高度（离人物更远）": "# Y-axis: 150-320 pixels above player (further from characters)",
    "# 确保不超出屏幕边界": "# Ensure within screen boundaries",
    "# 检查是否与已有蝴蝶重叠（最小间距70像素）": "# Check overlap with existing butterflies (min spacing 70px)",
    "# 优先生成数量较少的颜色，确保均衡": "# Prioritize generating fewer color, ensure balance",
    "# 第三关的蝴蝶会移动": "# Level 3 butterflies move",
    "# 倒计时结束，开始游戏": "# Countdown finished, start game",
    "# 播放开始音效": "# Play start sound",
    "# 当数字改变时播放倒计时音效": "# Play countdown sound when number changes",
    "# 生成蝴蝶": "# Generate butterflies",
    "# 检测碰撞并分离": "# Detect collision and separate",
    "# 检查所有蝴蝶对": "# Check all butterfly pairs",
    "# 计算距离": "# Calculate distance",
    "# 如果距离小于最小间距": "# If distance less than minimum",
    "# 计算分离向量": "# Calculate separation vector",
    "# 归一化": "# Normalize",
    "# 分离": "# Separate",
    "# 还没有玩家提交": "# No player has submitted yet",
    "# 所有玩家都提交了": "# All players submitted",
    "# 如果任何一个玩家答对了，播放成功音效": "# If any player correct, play success sound",
    "# 如果两个玩家都答错了，播放错误音效": "# If both players wrong, play error sound",
    "# 清空输入": "# Clear inputs",
    "# 显示结果": "# Show results",
    "# 延长结果显示时间": "# Extend result display time",
    "# 检查是否完成所有关卡": "# Check if all levels completed",
    "# 开始新关卡": "# Start new level",
    "# 前进到下一关": "# Progress to next level",
    "# 缩短一秒": "# Reduce by 1 second",
    "# 重置玩家输入": "# Reset player inputs",
    "# 绘制背景": "# Draw background",
    "# 绘制开始画面": "# Draw start screen",
    "# 绘制倒计时": "# Draw countdown",
    "# 绘制游戏界面": "# Draw game interface",
    "# 绘制输入界面": "# Draw input interface",
    "# 绘制结果界面": "# Draw result interface",
    "# 绘制游戏结束界面": "# Draw game over interface",
    "# 绘制暂停界面": "# Draw pause screen",
    "# 绘制半透明黑色遮罩": "# Draw semi-transparent black overlay",
    "# 绘制\"PAUSED\"标题": "# Draw \"PAUSED\" title",
    "# 添加阴影": "# Add shadow",
    "# 绘制提示信息": "# Draw hint message",
    "# 显示当前关卡和分数": "# Show current level and scores",
    "# 主游戏循环": "# Main game loop",
    "# 退出游戏": "# Exit game",
    "# 开始游戏": "# Start game",
    "# 暂停/恢复游戏": "# Pause/Resume game",
    "# 保存暂停前的状态": "# Save state before pause",
    "# 暂停音乐": "# Pause music",
    "# 恢复到暂停前的状态": "# Resume to state before pause",
    "# 恢复音乐": "# Resume music",
    "# 如果已暂停，不更新游戏逻辑": "# If paused, don't update game logic",
    "# 更新游戏逻辑": "# Update game logic",
    "# 绘制游戏画面": "# Draw game screen",
    "# 如果已暂停，绘制暂停界面": "# If paused, draw pause screen",
    "# 更新显示": "# Update display",
    "# 控制帧率": "# Control frame rate",
    "# Countdown结束，开始游戏": "# Countdown finished, start game",
    "# 更新蝴蝶": "# Update butterflies",
    "# 第三关：检查移动的蝴蝶是否会重叠，如果太近则反弹": "# Level 3: Check if moving butterflies overlap, bounce if too close",
    "# 最小间距70像素": "# Minimum spacing 70 pixels",
    "# 计算反弹方向": "# Calculate bounce direction",
    "# 反弹（交换并反向速度分量）": "# Bounce (swap and reverse velocity components)",
    "# Separate重叠的蝴蝶": "# Separate overlapping butterflies",
    "# 检查是否所有蝴蝶都消失了": "# Check if all butterflies disappeared",
    "# 10秒输入时间": "# 10 seconds input time",
    "# 是否显示结果": "# Whether to show result",
    "# 结果显示计时器": "# Result display timer",
    "# 如果正在显示结果，倒计时后进入下一关": "# If showing result, countdown then next level",
    "# 更新输入计时器": "# Update input timer",
    "# 更新玩家输入": "# Update player input",
    "# 检查是否时间到或两个玩家都已提交": "# Check if time's up or both players submitted",
    "# Show results4秒": "# Show results for 4 seconds",
    "# 计算得分": "# Calculate scores",
    "# 播放音效": "# Play sound effects",
    "# 至少有一人正确，播放成功音效": "# At least one correct, play success sound",
    "# 两人都错误，播放错误音效": "# Both wrong, play error sound",
    "# 两个都正确，先提交的得10分，后提交的得5分": "# Both correct, first submitter gets 10 pts, second gets 5 pts",
    "# 只有一个正确": "# Only one correct",
    "# 两个都错误": "# Both wrong",
    "# 未提交视为错误": "# Not submitted treated as wrong",
    "# 按时间加分": "# Add bonus points by time",
    "# 蝴蝶数量": "# Butterfly count",
    "# 正确答案": "# Correct answer",
    "# 每秒消耗的输入时间": "# Input time consumed per second",
    "# 输入时间结束": "# Input time ended",
    "# 绘制状态栏": "# Draw status bar",
    "# 绘制蝴蝶": "# Draw butterflies",
    "# 绘制玩家": "# Draw players",
    "# 倒计时数字": "# Countdown number",
    "# 根据倒计时数字设置颜色": "# Set color based on countdown number",
    "# 黄色": "# Yellow",
    "# 橙色": "# Orange",
    "# 红色": "# Red",
    "# 浅灰色": "# Light gray",
    "# 绘制倒计时数字（带描边）": "# Draw countdown number (with outline)",
    "# 绘制玩家信息和输入框": "# Draw player info and input boxes",
    "# 玩家的横向中心位置": "# Player horizontal center position",
    "# 输入框Y坐标": "# Input box Y coordinate",
    "# 输入框尺寸": "# Input box size",
    "# 绘制输入框": "# Draw input box",
    "# 绘制输入框背景": "# Draw input box background",
    "# 绘制输入框边框": "# Draw input box border",
    "# 绘制输入值": "# Draw input value",
    "# 绘制提示文字": "# Draw hint text",
    "# 绘制计时器": "# Draw timer",
    "# 绘制状态文字": "# Draw status text",
    "# 结果文字": "# Result text",
    "# 得分文字": "# Score text",
    "# 绘制标题": "# Draw title",
    "# 使用金色和紫色标题": "# Use gold and purple title",
    "# 绘制最终分数": "# Draw final scores",
    "# 绘制胜负判定": "# Draw win/lose determination",
    "# 绘制提示": "# Draw hint",
}

def translate_file():
    """Read file, translate comments, and write back"""
    filepath = "counting_butterfly.py"
    
    # Read the file
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Replace all translations
    for chinese, english in translations.items():
        content = content.replace(chinese, english)
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✓ Translated {len(translations)} comments in {filepath}")

if __name__ == "__main__":
    translate_file()
